feat: check for key mutation when removing children
widgetti/reacton pull request #35
Opened 2024-04-17 16:12 UTC by iisakkirotko

2024-04-17 16:12 UTC, iisakkirotko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/reacton/35?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#35** <a href="https://app.graphite.dev/github/pr/widgetti/reacton/35?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#34** <a href="https://app.graphite.dev/github/pr/widgetti/reacton/34?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @iisakkirotko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-25 16:28 UTC, maartenbreddels requested changes
Awesome to see this nice and clean PR after all this work :)
Please squash the 2 commits into 1, I see the test as part of the feature.
🥳

2024-04-25 16:28 UTC, maartenbreddels commented on reacton/core_test.py
> +def test_key_mutate_and_reuse(Container):
```suggestion
def test_key_mutate_protection(Container):
```

2024-04-26 08:13 UTC, maartenbreddels approved these changes

2024-04-26 09:51 UTC, iisakkirotko commented
### Merge activity

* **Apr 26, 5:51 AM EDT**: @iisakkirotko started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/widgetti/reacton/35).

2024-04-26 09:56 UTC, merged